Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "AllowEmptyInput" "false"
EndSection
Section "ServerLayout"
    Identifier "oxwasm"
    Screen "screen"
    InputDevice "kbd" "CoreKeyboard"
    InputDevice "mouse" "CorePointer"
    InputDevice "mouse2" "SendCoreEvents"
EndSection
Section "Device"
    Identifier "vesa"
    Driver "vesa"
EndSection
Section "Screen"
    Identifier "screen"
    Device "vesa"
    DefaultDepth 24
    SubSection "Display"
        Modes "1024x768"
    EndSubSection
EndSection
Section "InputDevice"
    Identifier "kbd"
    Driver "evdev"
    Option "Device" "/dev/input/event0"
EndSection
Section "InputDevice"
    Identifier "mouse"
    Driver "evdev"
    Option "Device" "/dev/input/event1"
EndSection
Section "InputDevice"
    Identifier "mouse2"
    Driver "evdev"
    Option "Device" "/dev/input/event2"
EndSection
